import Link from 'next/link';
import Image from 'next/image';
import { ArrowIcon, StarIcon } from '@/components/icons';
import { projects, teardowns, practice, process as workProcess, learning, recommendations, featuredProjects } from '@/content/site';
import { Arrow, Eyebrow, ProjectCard, TeardownCard, SectionHeading, ContactInvite, ResumeAction } from '@/components/ui';
export default function Home(){return <>
<section className="hero container"><div className="hero-copy"><div className="availability"><span/>Open to Product Management and Technical Product opportunities</div><p className="hero-intro">HELLO, I’M</p><h1>Iretioluwa<br/><em>Ogunmola<span>.</span></em></h1><p className="positioning">Product Manager <span>|</span> Technical Product Delivery<br className="desktop-break"/> & AI-Assisted Prototyping</p><p className="hero-description">I turn customer problems into clear product decisions and useful digital experiences.</p><p className="hero-context">Based in Abuja, Nigeria. I bring customer understanding, clear requirements and hands-on product delivery to teams building something that matters.</p><div className="actions"><Link className="button" href="/case-studies/">View My Work <Arrow/></Link><Link className="button outline" href="/contact/">Let’s Talk <Arrow/></Link><ResumeAction/></div></div><figure className="hero-portrait"><Image src="/images/iretioluwa-ogunmola.webp" alt="Iretioluwa Ogunmola" width={900} height={1032} preload sizes="(max-width: 767px) 100vw, 45vw"/><figcaption><span>Iretioluwa Ogunmola</span><span>ABUJA, NIGERIA</span></figcaption></figure><div className="hero-bottom"><span>Customer-led discovery</span><span>Technical product delivery</span><span>AI-assisted prototyping</span><span className="scroll-note">EXPLORE BELOW ↓</span></div></section>
<section className="practice-section container" data-reveal><div><Eyebrow>CURRENT SKILLS & PRACTICE</Eyebrow><h2>Clarity at every<br/><em>stage of product.</em></h2><p>I work with users, stakeholders and engineering teams to understand what needs to change and define what to build.</p></div><div className="skills">{practice.map((skill,i)=><span key={skill} style={{'--stagger':`${i*35}ms`} as React.CSSProperties}>{skill}<ArrowIcon/></span>)}</div></section>
<section className="highlights-section"><div className="container"><SectionHeading eyebrow="FROM RESEARCH TO REAL USE" title="Products and decisions I’ve helped move forward"/><div className="work-strip">{featuredProjects.map(p=><Link key={p.slug} href={`/case-studies/${p.slug}/`}><strong>{p.name==='Mikaelson Initiative Website'?'Mikaelson':p.name}</strong><span>{p.status}</span></Link>)}</div><div className="outcomes"><div><span className="tiny">PROPERTYBRIDGE · EARLY COMMERCIAL RESULTS</span><div className="metric-pair"><div><strong>{projects[0].revenueDisplay}</strong><span>reported revenue</span></div><div><strong>11</strong><span>product demos</span></div></div><p>Demo reporting: July 20–October 7, 2026.</p></div><div><span className="tiny">CHAYIM · RESULTS-ACCESS JOURNEY</span><strong className="big-metric">~10 <span>→</span> 1</strong><p>Weekly client complaints about accessing results after journey improvements.</p></div></div><div className="growth-note"><strong>PropertyBridge growth:</strong> +138% site sessions · +230% new users. <span>August 1–31 vs July 20–31, 2026. July is a partial month (12 days); these are total-period figures, not equal-duration or daily-normalised comparisons.</span></div></div></section>
<section className="section container"><SectionHeading eyebrow="DECISIONS, DELIVERY & LEARNING" title="A closer look at my work" description="The problem, my contribution and what changed." href="/case-studies/" action="All case studies"/><div className="project-grid featured-project-grid">{featuredProjects.map(p=><ProjectCard key={p.slug} project={p}/>)}</div></section>
<section className="teardown-section"><div className="container"><SectionHeading eyebrow="UNDERSTANDING PRODUCT DECISIONS" title="Looking closely. Thinking differently." description="Independent and collaborative analyses, with recommendations rather than shipped changes." href="/teardowns/" action="All teardowns"/><div className="teardown-grid">{[teardowns[2],teardowns[0],teardowns[1]].map(t=><TeardownCard key={t.slug} item={t}/>)}</div></div></section>
<section className="section container"><SectionHeading eyebrow="HOW I WORK" title="Start with the person. Follow through." description="Make the decision clear—and stay close to the experience."/><div className="process-grid">{workProcess.map(([name,copy,deliverables],i)=><article className="process-card" key={name} data-reveal><span className="process-number">0{i+1}</span><h3>{name}</h3><p>{copy}</p><span className="process-deliverables">{deliverables}</span></article>)}</div></section>
{recommendations.length>0&&<section className="section container"><SectionHeading eyebrow="RECOMMENDATIONS" title="Working together, in their words"/><div className="project-grid">{recommendations.map(r=><figure key={r.name} className="quote-card"><blockquote>{r.quote}</blockquote><figcaption>{r.name} · {r.role}<br/>{r.relationship} · {r.project}</figcaption></figure>)}</div></section>}
<section className="learning-section"><div className="container"><SectionHeading eyebrow="ALWAYS LEARNING" title="Building deeper technical confidence" description="Developing my practice through purposeful learning and hands-on exploration."/><div className="learning-grid">{learning.map(([title,copy,status],i)=><article key={title} data-reveal><span className="learning-icon" aria-hidden="true">{i%2===0?<ArrowIcon/>:<StarIcon/>}</span><span className="tiny">{status}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="learning-footnote">My interest in Forward Deployed Product Management is developing: understanding customers in context and helping turn operational needs into usable solutions.</p></div></section>
<ContactInvite/></>}
