import Link from 'next/link';
import Image from 'next/image';
import { ArrowIcon, StarIcon } from './icons';
import { projects, resume, site, type Project, type Teardown } from '@/content/site';
export function Arrow() {return <span className="arrow"><ArrowIcon/></span>}
export function ResumeAction(){return resume.available?<a className="text-link" href={resume.path} download>View Resume <ArrowIcon down/></a>:null;}
export function Eyebrow({children}:{children:React.ReactNode}){return <p className="eyebrow"><span aria-hidden="true"/>{children}</p>}
export function SectionHeading({eyebrow,title,description,href,action}:{eyebrow:string;title:string;description?:string;href?:string;action?:string}) {return <div className="section-heading" data-reveal><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2>{description&&<p className="section-intro">{description}</p>}</div>{href&&<Link className="text-link" href={href}>{action}<Arrow/></Link>}</div>}
export function Status({text}:{text:string}){return <span className={`status ${text.startsWith('Live')?'live':text.includes('development')?'development':'study'}`}><span aria-hidden="true"/>{text}</span>}
export function ProjectArt({project}:{project:Project}){
 if(project.image)return <figure className={`project-art supplied-art art-${project.slug}`}><Image src={project.image.src} alt={project.image.alt} width={project.image.width} height={project.image.height} sizes="(max-width: 767px) 100vw, 40vw"/><figcaption>{project.image.caption}</figcaption></figure>;
 const code = {'propertybridge':'PB','chayim-diagnostics':'ch','learned':'Le','afribite':'ab','travelmet':'tm','mikaelson-initiative':'mi','rio-ai':'rio','groomingher':'gh'}[project.slug];
 return <div className={`project-art art-${project.slug}`} aria-hidden="true"><div className="art-grid"/><span className="art-sector">{project.sector}</span><div className="art-orbit orbit-one"/><div className="art-orbit orbit-two"/><div className="art-icon">{code}<span><StarIcon/></span></div><div className="art-bottom"><span>{project.name}</span><span>{project.year}</span></div></div>;
}
export function ProjectCard({project,compact=false}:{project:Project;compact?:boolean}){return <article className={`project-card ${compact?'compact':''}`} data-reveal><Link className="art-link" href={`/case-studies/${project.slug}/`} aria-label={`Read ${project.name} case study`}><ProjectArt project={project}/></Link><div className="card-body"><div className="card-meta"><span>{project.sector} / {project.year}</span></div><Status text={project.status}/><h3><Link href={`/case-studies/${project.slug}/`}>{project.name}</Link></h3><p>{project.summary}</p><p className="card-role">{project.role}</p>{project.url&&<a className="text-link card-product-link" href={project.url} target="_blank" rel="noopener noreferrer">{project.linkLabel}<Arrow/></a>}<div className="card-bottom"><span className="card-highlight">{project.highlight}</span><Link className="circle-link" href={`/case-studies/${project.slug}/`} aria-label={`Read ${project.name} story`}><Arrow/></Link></div></div></article>}
export function TeardownCard({item}:{item:Teardown}){return <article className={`teardown-card teardown-${item.slug}`} data-reveal><div className="teardown-top"><span className="teardown-wordmark" aria-hidden="true">{item.name==='Canva'?'Canva':item.name==='Claude AI'?'Claude':item.name==='Uber vs Bolt'?'Uber / Bolt':'Let’sChat'}</span><span className="tiny">{item.year}</span></div><div className="teardown-content"><span className="tiny">{item.focus}</span><h3><Link href={`/teardowns/${item.slug}/`}>{item.headline}</Link></h3><p>{item.summary}</p><Link className="text-link" href={`/teardowns/${item.slug}/`}>Explore teardown <Arrow/></Link></div></article>}
export function ContactInvite(){return <section className="contact-invite container" data-reveal><div className="contact-decoration" aria-hidden="true"><StarIcon/></div><div><Eyebrow>GOOD PRODUCTS START WITH A CONVERSATION</Eyebrow><h2>Building something useful?<br/><em>Let’s talk.</em></h2><p>I’m open to product roles and collaborations where customer insight, clear delivery and thoughtful technology can make a difference.</p><div className="actions"><Link className="button" href="/contact/">Let’s Talk <Arrow/></Link><ResumeAction/></div></div><span className="contact-location">ABUJA, NIGERIA · OPEN TO REMOTE</span></section>}
export function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-top"><div><Link href="/" className="footer-name">Ireti Ogunmola<span>.</span></Link><p>Product Manager · Technical product delivery<br/>AI-assisted prototyping</p><a href={`mailto:${site.email}`} className="text-link">{site.email}<Arrow/></a></div><div className="footer-links"><Link href="/about/">About</Link><Link href="/products/">Products</Link><Link href="/case-studies/">Case Studies</Link><Link href="/teardowns/">Teardowns</Link><Link href="/contact/">Contact</Link><ResumeAction/></div><div className="footer-links"><span className="tiny">ELSEWHERE</span><a href={site.github} target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href={site.phoneHref}>{site.phone}</a><span>Abuja, Nigeria</span></div></div><div className="footer-bottom"><span>© 2026 Iretioluwa Ogunmola.</span><span>Thoughtful products. Meaningful experiences.</span><Link href="/">Back to home ↑</Link></div></div></footer>}
export function PageIntro({eyebrow,title,emphasis,description}:{eyebrow:string;title:string;emphasis?:string;description:string}){return <section className="page-intro container"><Eyebrow>{eyebrow}</Eyebrow><h1>{title} {emphasis&&<em>{emphasis}</em>}</h1><p>{description}</p></section>}
export function NextProject({slug}:{slug:string}){const index=projects.findIndex(p=>p.slug===slug);const next=projects[(index+1)%projects.length];return <Link className="next-story" href={`/case-studies/${next.slug}/`}><span><span className="tiny">NEXT PROJECT</span><strong>{next.name}</strong></span><Arrow/></Link>}
